[package]
name = "simplealloc"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
repository.workspace = true
publish = false

[dependencies]

[features]
default = ["thread-safe"]
thread-safe = []
