#!/usr/bin/ruby

require "fileutils"

rust = ["// This file was AUTOGENERATED. DO NOT EDIT."]

Dir["tests/*/*.S"].each do |path|
    _, category, filename = path.split("/")
    name = filename.sub(".S", "")
    output_path = "output/#{category}/#{name}.elf"

    if path =~ /rv64/
        march = "rv64"
        mabi = "lp64"
    else
        march = "rv32"
        mabi = "ilp32"
    end

    march += "ima_zifencei"

    FileUtils.mkdir_p File.dirname(output_path)
    if !File.exist?(output_path) || ARGV.include?("--force")
        puts "Building test: #{category}/#{name}"
        system "riscv64-elf-gcc -fPIE -fvisibility=hidden -march=#{march} -mabi=#{mabi} -I. -Itests/macros/scalar -ffreestanding -nostdlib -nostartfiles #{path} -o #{output_path} -Wl,--emit-relocs"
        if $?.exitstatus != 0
            puts "ERROR: building failed!"
            exit 1
        end
    else
        puts "Skipping building (already built): #{category}/#{name}"
    end

    rust << "riscv_test!(riscv_#{category}_#{name}, \"../../../guest-programs/riscv-tests/output/#{category}/#{name}.elf\");"
end

File.write "../../crates/polkavm/src/tests_riscv.rs", rust.join("\n")
