[package]
name = "polkavm-linux-raw-generate"
version = "0.1.0"
authors = ["Jan Bujak <jan@parity.io>", "Parity Technologies <admin@parity.io>"]
license = "MIT/Apache-2.0"
edition = "2021"
publish = false

[dependencies]
bindgen = "0.69.4"
