[build]
target = "riscv32emac-unknown-none-polkavm"

[target.riscv32emac-unknown-none-polkavm]
rustflags = [
    "-C", "relocation-model=pie",
    "-C", "link-arg=--emit-relocs",
    "-C", "link-arg=--unique",
]
